language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-text --exclude-group internet

cache:
  directories:
    - "$HOME/.composer/cache/files"
