language: php

php:
  - 5.3.3
  - 5.3
  - 5.4

before_script:
  - sudo apt-get install -y libevent-dev
  - sh -c " if [ \"\$(php --re libevent | grep 'does not exist')\" != '' ]; then
              (yes '' | pecl install libevent-beta)
            fi"
  - composer self-update
  - composer install --dev --prefer-source

script: phpunit --coverage-text
