language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

install:
  - ./tests/travis-init.sh

script:
  - php vendor/bin/phpunit --coverage-text
