language: php

php:
# - 5.3 # requires old distro, see below
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

# lock distro so new future defaults will not break the build
dist: trusty

matrix:
  include:
    - php: 5.3
      dist: precise
  allow_failures:
    - php: hhvm

install:
  - composer install --no-interaction

script:
  - php vendor/bin/phpunit --coverage-text --exclude-group internet
